// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package class_room

import (
	"gorm.io/gorm"
	"online-course/internal/class_room/delivery/http"
	class_room2 "online-course/internal/class_room/repository"
	class_room3 "online-course/internal/class_room/usecase"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *class_room.ClassRoomHandler {
	classRoomRepository := class_room2.NewClassRoomRepository(db)
	classRoomUsecase := class_room3.NewClassRoomUseCase(classRoomRepository)
	classRoomHandler := class_room.NewClassRoomHandler(classRoomUsecase)
	return classRoomHandler
}
