// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package verification_email

import (
	"gorm.io/gorm"
	"online-course/internal/user/repository"
	user2 "online-course/internal/user/usecase"
	"online-course/internal/verification_email/delivery/http"
	verification_email2 "online-course/internal/verification_email/usecase"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *verification_email.VerificationEmailHandler {
	userRepository := user.NewUserRepository(db)
	userUsecase := user2.NewUserUseCase(userRepository)
	verificationEmailUsecase := verification_email2.NewVerificationEmailUsecase(userUsecase)
	verificationEmailHandler := verification_email.NewVerificationEmailHandler(verificationEmailUsecase)
	return verificationEmailHandler
}
