// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product_category

import (
	"gorm.io/gorm"
	"online-course/internal/product_category/delivery/http"
	product_category2 "online-course/internal/product_category/repository"
	product_category3 "online-course/internal/product_category/usecase"
	"online-course/pkg/media/cloudinary"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *product_category.ProductCategoryHandler {
	productCategoryRepository := product_category2.NewProductCategoryRepository(db)
	mediaMedia := media.NewMedia()
	productCategoryUsecase := product_category3.NewProductCategoryUsecase(productCategoryRepository, mediaMedia)
	productCategoryHandler := product_category.NewProductCategoryHandler(productCategoryUsecase)
	return productCategoryHandler
}
