CREATE TABLE orders (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id`INT NULL,
    `discount_id` INT NULL,
    `checkout_link` VARCHAR ( 255 ) NULL,
    `external_id` VARCHAR ( 255 ) NULL,
    `price` INT NOT NULL,
    `total_price` INT NOT NULL,
    `status` VARCHAR ( 255 ) NOT NULL,
    `created_by` INT NULL,
    `updated_by` INT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY ( `id` ),
    INDEX idx_orders_user_id ( `user_id` ) ,
    INDEX idx_orders_discount_id ( `discount_id` ) ,
    INDEX idx_orders_created_by ( `created_by` ) ,
    INDEX idx_orders_updated_by ( `updated_by` ) ,
    CONSTRAINT FK_orders_user_id FOREIGN KEY (`user_id`) REFERENCES users(`id`)  ON DELETE SET NULL,
    CONSTRAINT FK_orders_discount_id FOREIGN KEY (`discount_id`) REFERENCES discounts(`id`)  ON DELETE SET NULL,
    CONSTRAINT FK_orders_created_by FOREIGN KEY (`created_by`) REFERENCES users(`id`)  ON DELETE SET NULL,
    CONSTRAINT FK_orders_updated_by FOREIGN KEY (`updated_by`) REFERENCES users(`id`)  ON DELETE SET NULL
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;