CREATE TABLE oauth_clients (
    `id` INT NOT NULL AUTO_INCREMENT,
    `client_id` VARCHAR ( 255 ) NOT NULL,
    `client_secret` VARCHAR ( 255 ) NOT NULL,
    `name` VARCHAR ( 255 ) NOT NULL,
    `redirect` VARCHAR ( 255 )  NULL,
    `description` VARCHAR ( 255 )  NULL,
    `scope` VARCHAR ( 255 )  NULL,
    `created_by` INT NULL,
    `updated_by` INT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY ( `id` ),
    UNIQUE KEY oauth_clients_client_id_unique ( `client_id` ),
    INDEX idx_oauth_clients_client_id ( `client_id` ) ,
    INDEX idx_oauth_client_created_by ( `created_by` ) ,
    INDEX idx_oauth_client_updated_by ( `updated_by` ) ,
    CONSTRAINT FK_oauth_clients_created_by FOREIGN KEY (`created_by`) REFERENCES admins(`id`)  ON DELETE SET NULL,
    CONSTRAINT FK_oauth_clients_updated_by FOREIGN KEY (`updated_by`) REFERENCES admins(`id`)  ON DELETE SET NULL
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;