// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package forgot_password

import (
	"gorm.io/gorm"
	"online-course/internal/forgot_password/delivery/http"
	forgot_password2 "online-course/internal/forgot_password/repository"
	forgot_password3 "online-course/internal/forgot_password/usecase"
	"online-course/internal/user/repository"
	user2 "online-course/internal/user/usecase"
	"online-course/pkg/mail/sendgrid"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *forgot_password.ForgotPasswordHandler {
	forgotPasswordRepository := forgot_password2.NewForgotPasswordRepository(db)
	userRepository := user.NewUserRepository(db)
	userUsecase := user2.NewUserUseCase(userRepository)
	mailMail := mail.NewMail()
	forgotPasswordUsecase := forgot_password3.NewForgotPasswordUsecase(forgotPasswordRepository, userUsecase, mailMail)
	forgotPasswordHandler := forgot_password.NewForgotPasswordHandler(forgotPasswordUsecase)
	return forgotPasswordHandler
}
